import {
  GraphQLEnumType,
  GraphQLInputObjectType,
  GraphQLInterfaceType,
  GraphQLNamedType,
  GraphQLObjectType,
  GraphQLScalarType,
  GraphQLSchema,
  GraphQLType,
  GraphQLUnionType,
  getNamedType,
  isEnumType,
  isInputObjectType,
  isInterfaceType,
  isListType,
  isNonNullType,
  isObjectType,
  isScalarType,
  isSpecifiedScalarType,
  isUnionType,
} from 'graphql';
import { ResolvedConfig } from './config';
import { findHeuristicExpression, ScalarCategory } from './heuristics';

/** Type-based fallbacks for the built-in scalars (used when no heuristic matches). */
export const BUILTIN_SCALAR_FALLBACKS: Record<string, string> = {
  ID: 'faker.string.uuid()',
  String: 'faker.lorem.word()',
  Int: 'faker.number.int()',
  Float: 'faker.number.float()',
  Boolean: 'faker.datatype.boolean()',
};

/** Built-in defaults for common custom scalars; user `scalars` config merges over these. */
export const DEFAULT_CUSTOM_SCALARS: Record<string, string> = {
  DateTime: 'faker.date.recent().toISOString()',
  Date: 'faker.date.recent().toISOString().slice(0, 10)',
  Time: 'faker.date.recent().toISOString().slice(11)',
  JSON: '{}',
  JSONObject: '{}',
  BigInt: 'faker.number.int()',
  UUID: 'faker.string.uuid()',
};

/** Fallback for custom scalars with no built-in or configured expression. */
const UNKNOWN_SCALAR_FALLBACK = 'faker.lorem.word()';

type FactoryType =
  | GraphQLObjectType
  | GraphQLInputObjectType
  | GraphQLInterfaceType
  | GraphQLUnionType;

interface GeneratorContext {
  schema: GraphQLSchema;
  config: ResolvedConfig;
  scalarExpressions: Record<string, string>;
  /** Emitted-call-graph adjacency: factory type name → factory type names it calls. */
  adjacency: Map<string, Set<string>>;
  reachabilityCache: Map<string, boolean>;
  usedEnums: Set<string>;
}

export function generateMockBuilders(schema: GraphQLSchema, config: ResolvedConfig): string {
  const factoryTypes = collectFactoryTypes(schema);
  const ctx: GeneratorContext = {
    schema,
    config,
    scalarExpressions: { ...DEFAULT_CUSTOM_SCALARS, ...config.scalars },
    adjacency: buildAdjacency(schema, factoryTypes),
    reachabilityCache: new Map(),
    usedEnums: new Set(),
  };

  const factories = factoryTypes.map((type) => generateFactory(type, ctx));

  const header: string[] = [
    '/* eslint-disable */',
    '// Generated by graphql-codegen-mock-builder. Do not edit manually.',
    "import { faker } from '@faker-js/faker';",
  ];
  if (config.typesFile) {
    const typeNames = factoryTypes.map((t) => tsTypeName(t.name, config));
    const enumNames = [...ctx.usedEnums].map((name) => tsTypeName(name, config));
    // Under 'ts-enum', enum members are referenced at runtime, so enums need a
    // value import; under 'union', everything is type-only.
    const typeOnly =
      config.enumStyle === 'ts-enum' ? typeNames : [...typeNames, ...enumNames];
    header.push(
      `import type { ${[...new Set(typeOnly)].sort().join(', ')} } from '${config.typesFile}';`
    );
    if (config.enumStyle === 'ts-enum' && enumNames.length > 0) {
      header.push(
        `import { ${[...new Set(enumNames)].sort().join(', ')} } from '${config.typesFile}';`
      );
    }
  }

  return `${header.join('\n')}\n\n${factories.join('\n\n')}\n`;
}

/** All object, input object, interface, and union types, sorted by name. */
function collectFactoryTypes(schema: GraphQLSchema): FactoryType[] {
  return Object.values(schema.getTypeMap())
    .filter((type): type is FactoryType => isFactoryType(type))
    .sort((a, b) => a.name.localeCompare(b.name));
}

function isFactoryType(type: GraphQLNamedType): type is FactoryType {
  if (type.name.startsWith('__')) return false;
  return (
    isObjectType(type) || isInputObjectType(type) || isInterfaceType(type) || isUnionType(type)
  );
}

function factoryName(typeName: string, config: ResolvedConfig): string {
  return `${config.namePrefix}${typeName}${config.nameSuffix}`;
}

/** GraphQL type name → TypeScript type name, honoring the `typescript` plugin's typesPrefix/typesSuffix. */
function tsTypeName(typeName: string, config: ResolvedConfig): string {
  return `${config.typesPrefix}${typeName}${config.typesSuffix}`;
}

function sortedFields(type: GraphQLObjectType | GraphQLInputObjectType | GraphQLInterfaceType) {
  return Object.values(type.getFields()).sort((a, b) => a.name.localeCompare(b.name));
}

/** Interfaces/unions delegate to their first (alphabetical) concrete member, if any. */
function delegateTarget(
  type: GraphQLInterfaceType | GraphQLUnionType,
  schema: GraphQLSchema
): GraphQLObjectType | undefined {
  const possible = [...schema.getPossibleTypes(type)].sort((a, b) => a.name.localeCompare(b.name));
  return possible[0];
}

// --- Cycle detection over the emitted call graph -------------------------------------------

function buildAdjacency(
  schema: GraphQLSchema,
  factoryTypes: FactoryType[]
): Map<string, Set<string>> {
  const adjacency = new Map<string, Set<string>>();
  for (const type of factoryTypes) {
    const edges = new Set<string>();
    if (isUnionType(type)) {
      const target = delegateTarget(type, schema);
      if (target) edges.add(target.name);
    } else if (isInterfaceType(type) && delegateTarget(type, schema)) {
      edges.add(delegateTarget(type, schema)!.name);
    } else {
      // Object, input object, or implementation-less interface: calls the
      // factory of every composite field target.
      for (const field of Object.values(type.getFields())) {
        const named = getNamedType(field.type as GraphQLType);
        if (isFactoryType(named)) edges.add(named.name);
      }
    }
    adjacency.set(type.name, edges);
  }
  return adjacency;
}

/** True when `from`'s factory (transitively) calls `to`'s factory. */
function canReach(from: string, to: string, ctx: GeneratorContext): boolean {
  const cacheKey = `${from}->${to}`;
  const cached = ctx.reachabilityCache.get(cacheKey);
  if (cached !== undefined) return cached;

  const stack = [...(ctx.adjacency.get(from) ?? [])];
  const seen = new Set(stack);
  let result = false;
  while (stack.length > 0) {
    const current = stack.pop()!;
    if (current === to) {
      result = true;
      break;
    }
    for (const next of ctx.adjacency.get(current) ?? []) {
      if (!seen.has(next)) {
        seen.add(next);
        stack.push(next);
      }
    }
  }
  ctx.reachabilityCache.set(cacheKey, result);
  return result;
}

// --- Factory emission -----------------------------------------------------------------------

function generateFactory(type: FactoryType, ctx: GeneratorContext): string {
  const name = factoryName(type.name, ctx.config);
  const tsName = tsTypeName(type.name, ctx.config);
  const signature = `export function ${name}(overrides?: Partial<${tsName}>): ${tsName}`;

  if (isUnionType(type)) {
    const target = delegateTarget(type, ctx.schema);
    const base = target ? `...${factoryName(target.name, ctx.config)}(),\n    ` : '';
    return `${signature} {\n  return {\n    ${base}...overrides,\n  } as ${tsName};\n}`;
  }

  if (isInterfaceType(type)) {
    const target = delegateTarget(type, ctx.schema);
    if (target) {
      return `${signature} {\n  return {\n    ...${factoryName(target.name, ctx.config)}(),\n    ...overrides,\n  };\n}`;
    }
    // Interface with no implementations: build its own fields (no __typename —
    // __typename must name a concrete object type).
  }

  const lines: string[] = [];
  if (isObjectType(type) && ctx.config.addTypename) {
    lines.push(`__typename: '${type.name}',`);
  }
  for (const field of sortedFields(type)) {
    lines.push(`${field.name}: ${fieldValueExpression(type.name, field.name, field.type, ctx)},`);
  }
  lines.push('...overrides,');

  const body = lines.map((line) => `    ${line}`).join('\n');
  return `${signature} {\n  return {\n${body}\n  };\n}`;
}

function fieldValueExpression(
  containerName: string,
  fieldName: string,
  fieldType: GraphQLType,
  ctx: GeneratorContext
): string {
  const nullable = !isNonNullType(fieldType);

  if (nullable && !ctx.config.includeNullableFields) return 'null';

  const named = getNamedType(fieldType);
  if (
    isFactoryType(named) &&
    ctx.config.terminateCircularRelationships &&
    canReach(named.name, containerName, ctx)
  ) {
    // Break the cycle: empty list, or null when nullable. NonNull non-list
    // circular fields fall through and recurse (documented limitation).
    if (containsList(fieldType)) return '[]';
    if (nullable) return 'null';
  }

  return typeValueExpression(fieldType, fieldName, ctx);
}

function containsList(type: GraphQLType): boolean {
  if (isNonNullType(type)) return containsList(type.ofType);
  return isListType(type);
}

function typeValueExpression(type: GraphQLType, fieldName: string, ctx: GeneratorContext): string {
  if (isNonNullType(type)) return typeValueExpression(type.ofType, fieldName, ctx);
  if (isListType(type)) {
    const element = typeValueExpression(type.ofType, fieldName, ctx);
    return `Array.from({ length: ${ctx.config.listLength} }, () => ${element})`;
  }
  if (isScalarType(type)) return scalarValueExpression(type, fieldName, ctx);
  if (isEnumType(type)) return enumValueExpression(type, ctx);
  // Object, input object, interface, or union: call its factory.
  return `${factoryName(type.name, ctx.config)}()`;
}

function scalarValueExpression(
  scalar: GraphQLScalarType,
  fieldName: string,
  ctx: GeneratorContext
): string {
  if (isSpecifiedScalarType(scalar)) {
    if (scalar.name !== 'Boolean') {
      const category: ScalarCategory =
        scalar.name === 'Int' || scalar.name === 'Float' ? 'number' : 'string';
      const heuristic = findHeuristicExpression(fieldName, category);
      if (heuristic) return heuristic;
    }
    return BUILTIN_SCALAR_FALLBACKS[scalar.name];
  }
  return ctx.scalarExpressions[scalar.name] ?? UNKNOWN_SCALAR_FALLBACK;
}

function enumValueExpression(enumType: GraphQLEnumType, ctx: GeneratorContext): string {
  ctx.usedEnums.add(enumType.name);
  const tsName = tsTypeName(enumType.name, ctx.config);

  if (ctx.config.enumStyle === 'ts-enum') {
    // Real TS enums reject string-literal casts (TS2352); reference members at
    // runtime instead — member-name-agnostic, so any enum naming convention works.
    if (ctx.config.enumsAsRandom) {
      return `faker.helpers.arrayElement(Object.values(${tsName})) as ${tsName}`;
    }
    return `Object.values(${tsName})[0] as ${tsName}`;
  }

  const values = enumType.getValues().map((value) => value.name);
  if (ctx.config.enumsAsRandom) {
    const list = values.map((value) => JSON.stringify(value)).join(', ');
    return `faker.helpers.arrayElement([${list}]) as ${tsName}`;
  }
  return `${JSON.stringify(values[0])} as ${tsName}`;
}
