import {
  DocumentNode,
  FieldNode,
  FragmentDefinitionNode,
  GraphQLCompositeType,
  GraphQLEnumType,
  GraphQLObjectType,
  GraphQLScalarType,
  GraphQLSchema,
  GraphQLType,
  InlineFragmentNode,
  OperationDefinitionNode,
  SelectionSetNode,
  getNamedType,
  isCompositeType,
  isEnumType,
  isInterfaceType,
  isListType,
  isNonNullType,
  isObjectType,
  isScalarType,
  isUnionType,
} from 'graphql';
import { DEFAULT_CUSTOM_SCALARS, ExprContext, enumValueExpression, scalarValueExpression } from './generate';
import { ResolvedConfig } from './config';
import { resolveNamingConvention } from './naming';

/** DocumentFile shape passed by graphql-codegen (only `document` is used). */
interface DocumentFileLike {
  document?: DocumentNode;
}

interface OpContext extends ExprContext {
  schema: GraphQLSchema;
  /** Fragment name → definition, for resolving `...Spread`s. */
  fragments: Map<string, FragmentDefinitionNode>;
  /** Namespace alias base types are imported under (near-operation-file: `Types`). */
  baseTypesNamespace: string;
  /** Whether faker was actually referenced (drives the import). */
  usedFaker: { value: boolean };
}

/** Entry point: emit a factory per fragment and operation across all documents. */
export function generateOperationMockBuilders(
  schema: GraphQLSchema,
  documents: DocumentFileLike[],
  config: ResolvedConfig
): string {
  const ctx: OpContext = {
    schema,
    config,
    convertName: resolveNamingConvention(config.namingConvention),
    scalarExpressions: { ...DEFAULT_CUSTOM_SCALARS, ...config.scalars },
    usedEnums: new Set(),
    fragments: collectFragments(documents),
    baseTypesNamespace: config.baseTypesNamespace ?? '',
    usedFaker: { value: false },
  };

  const blocks: string[] = [];
  for (const def of iterateDefinitions(documents)) {
    if (def.kind === 'FragmentDefinition') blocks.push(emitFragmentFactory(def, ctx));
    else if (def.kind === 'OperationDefinition' && def.name) blocks.push(emitOperationFactory(def, ctx));
  }

  const header: string[] = [
    '/* eslint-disable */',
    '// Generated by graphql-codegen-mock-builder (operations mode). Do not edit manually.',
  ];
  if (ctx.usedFaker.value) header.push("import { faker } from '@faker-js/faker';");
  if (config.typesFile) {
    // Standalone / separate-file mode: import the result types + any base enums.
    // (In near-operation-file/same-file mode `typesFile` is unset — the result
    // types are already in scope and enums come through the `Types` namespace.)
    const resultTypes = new Set<string>();
    for (const def of iterateDefinitions(documents)) {
      if (def.kind === 'FragmentDefinition') resultTypes.add(fragmentTypeName(def.name.value, ctx));
      else if (def.kind === 'OperationDefinition' && def.name)
        resultTypes.add(operationTypeName(def, ctx));
    }
    const enumNames = [...ctx.usedEnums].map((n) => tsBaseName(n, ctx));
    // ts-enum enums are referenced as runtime values (value import); union-style
    // enums are only used in `as` casts (type-only import).
    const typeOnly =
      config.enumStyle === 'ts-enum' ? [...resultTypes] : [...resultTypes, ...enumNames];
    header.push(`import type { ${[...new Set(typeOnly)].sort().join(', ')} } from '${config.typesFile}';`);
    if (config.enumStyle === 'ts-enum' && enumNames.length > 0) {
      header.push(`import { ${[...new Set(enumNames)].sort().join(', ')} } from '${config.typesFile}';`);
    }
  }

  return `${header.join('\n')}\n\n${blocks.join('\n\n')}\n`;
}

// --- naming ---------------------------------------------------------------------------------

/** A base (schema) type/enum name as referenced in this file — namespaced when applicable. */
function tsBaseName(typeName: string, ctx: OpContext): string {
  const local = `${ctx.config.typesPrefix}${ctx.convertName(typeName)}${ctx.config.typesSuffix}`;
  return ctx.baseTypesNamespace ? `${ctx.baseTypesNamespace}.${local}` : local;
}

/** Result type name of a fragment, mirroring `typescript-operations`. */
function fragmentTypeName(fragmentName: string, ctx: OpContext): string {
  return `${ctx.config.typesPrefix}${ctx.convertName(fragmentName)}${ctx.config.fragmentSuffix}${ctx.config.typesSuffix}`;
}

function operationKind(def: OperationDefinitionNode): string {
  return def.operation.charAt(0).toUpperCase() + def.operation.slice(1); // Query/Mutation/Subscription
}

/** Result type name of an operation, mirroring `typescript-operations`. */
function operationTypeName(def: OperationDefinitionNode, ctx: OpContext): string {
  const kind = ctx.config.omitOperationSuffix ? '' : operationKind(def);
  return `${ctx.config.typesPrefix}${ctx.convertName(def.name!.value)}${kind}${ctx.config.operationResultSuffix}${ctx.config.typesSuffix}`;
}

function fragmentFactoryName(fragmentName: string, ctx: OpContext): string {
  return `${ctx.config.namePrefix}${ctx.convertName(fragmentName)}${ctx.config.nameSuffix}`;
}

function operationFactoryName(def: OperationDefinitionNode, ctx: OpContext): string {
  return `${ctx.config.namePrefix}${ctx.convertName(def.name!.value)}${operationKind(def)}${ctx.config.nameSuffix}`;
}

// --- emission -------------------------------------------------------------------------------

function emitFragmentFactory(def: FragmentDefinitionNode, ctx: OpContext): string {
  const typeName = fragmentTypeName(def.name.value, ctx);
  const fnName = fragmentFactoryName(def.name.value, ctx);
  const parent = ctx.schema.getType(def.typeCondition.name.value);
  if (!parent || !isCompositeType(parent)) return `// (skipped ${fnName}: unknown type condition)`;
  const body = buildComposite(parent, def.selectionSet, ctx, 1);
  return factoryBlock(fnName, typeName, body);
}

function emitOperationFactory(def: OperationDefinitionNode, ctx: OpContext): string {
  const typeName = operationTypeName(def, ctx);
  const fnName = operationFactoryName(def, ctx);
  const root =
    def.operation === 'query'
      ? ctx.schema.getQueryType()
      : def.operation === 'mutation'
        ? ctx.schema.getMutationType()
        : ctx.schema.getSubscriptionType();
  if (!root) return `// (skipped ${fnName}: no ${def.operation} root type)`;
  const body = buildComposite(root, def.selectionSet, ctx, 1);
  return factoryBlock(fnName, typeName, body);
}

function factoryBlock(fnName: string, typeName: string, body: string): string {
  return `export function ${fnName}(overrides?: Partial<${typeName}>): ${typeName} {\n  return ${body};\n}`;
}

/**
 * Build an object-literal expression for `selectionSet` realized as one concrete
 * object type. Recurses the selection (not the schema type), so it always
 * terminates — even for schema types with reference cycles.
 */
function buildComposite(
  parent: GraphQLCompositeType,
  selectionSet: SelectionSetNode,
  ctx: OpContext,
  depth: number
): string {
  const concrete = resolveConcrete(parent, selectionSet, ctx);
  const fields = collectFields(concrete, selectionSet, ctx);

  const pad = '  '.repeat(depth + 1);
  const closePad = '  '.repeat(depth);
  const lines: string[] = [`__typename: '${concrete.name}',`];

  for (const [responseKey, field] of fields) {
    if (field.name.value === '__typename') continue; // already emitted
    const fieldDef = concrete.getFields()[field.name.value];
    if (!fieldDef) continue; // field not on the concrete type (skip)
    const value = field.selectionSet
      ? wrapField(fieldDef.type, () =>
          buildComposite(getNamedType(fieldDef.type) as GraphQLCompositeType, field.selectionSet!, ctx, depth + 1)
        , ctx)
      : wrapField(fieldDef.type, () => leafExpression(getNamedType(fieldDef.type), field.name.value, ctx), ctx);
    lines.push(`${responseKey}: ${value},`);
  }
  // Only the factory's root object accepts caller overrides; nested objects are
  // fully built from the selection set.
  if (depth === 1) lines.push('...overrides,');

  return `{\n${lines.map((l) => pad + l).join('\n')}\n${closePad}}`;
}

/** Pick the concrete object type to realize an abstract selection as. */
function resolveConcrete(
  parent: GraphQLCompositeType,
  selectionSet: SelectionSetNode,
  ctx: OpContext
): GraphQLObjectType {
  if (isObjectType(parent)) return parent;
  // interface/union: first inline fragment naming an object type wins; else first possible type.
  for (const sel of selectionSet.selections) {
    if (sel.kind === 'InlineFragment' && sel.typeCondition) {
      const t = ctx.schema.getType(sel.typeCondition.name.value);
      if (t && isObjectType(t)) return t;
    }
  }
  const possible = [...ctx.schema.getPossibleTypes(parent)].sort((a, b) => a.name.localeCompare(b.name));
  return possible[0];
}

/**
 * Flatten a selection set (following spreads + inline fragments applicable to
 * `concrete`) into an ordered response-key → field map. Later selections of the
 * same key overwrite earlier ones (matching GraphQL field merging closely enough).
 */
function collectFields(
  concrete: GraphQLObjectType,
  selectionSet: SelectionSetNode,
  ctx: OpContext,
  acc: Map<string, FieldNode> = new Map()
): Map<string, FieldNode> {
  for (const sel of selectionSet.selections) {
    if (sel.kind === 'Field') {
      acc.set(sel.alias?.value ?? sel.name.value, sel);
    } else if (sel.kind === 'InlineFragment') {
      if (appliesTo(concrete, sel, ctx)) collectFields(concrete, sel.selectionSet, ctx, acc);
    } else if (sel.kind === 'FragmentSpread') {
      const frag = ctx.fragments.get(sel.name.value);
      if (frag && appliesToNamed(concrete, frag.typeCondition.name.value, ctx)) {
        collectFields(concrete, frag.selectionSet, ctx, acc);
      }
    }
  }
  return acc;
}

function appliesTo(concrete: GraphQLObjectType, frag: InlineFragmentNode, ctx: OpContext): boolean {
  if (!frag.typeCondition) return true;
  return appliesToNamed(concrete, frag.typeCondition.name.value, ctx);
}

/** True when a fragment on `condName` applies to the concrete object type. */
function appliesToNamed(concrete: GraphQLObjectType, condName: string, ctx: OpContext): boolean {
  if (condName === concrete.name) return true;
  const cond = ctx.schema.getType(condName);
  if (!cond) return false;
  if (isInterfaceType(cond)) return concrete.getInterfaces().some((i) => i.name === condName);
  if (isUnionType(cond)) return ctx.schema.getPossibleTypes(cond).some((t) => t.name === concrete.name);
  return false;
}

// --- value expressions ----------------------------------------------------------------------

/** Apply list wrapping + nullable rules around an inner value expression. */
function wrapField(type: GraphQLType, inner: () => string, ctx: OpContext): string {
  const nullable = !isNonNullType(type);
  if (nullable && !ctx.config.includeNullableFields) return 'null';
  const build = (t: GraphQLType): string => {
    if (isNonNullType(t)) return build(t.ofType);
    // Parenthesize the arrow body so an object-literal element isn't parsed as a block.
    if (isListType(t)) return `Array.from({ length: ${ctx.config.listLength} }, () => (${build(t.ofType)}))`;
    return inner();
  };
  return build(type);
}

function leafExpression(named: GraphQLType, fieldName: string, ctx: OpContext): string {
  if (isScalarType(named)) {
    ctx.usedFaker.value = true;
    return scalarValueExpression(named as GraphQLScalarType, fieldName, ctx);
  }
  if (isEnumType(named)) {
    const expr = enumValueExpression(named as GraphQLEnumType, ctx);
    if (expr.includes('faker.')) ctx.usedFaker.value = true;
    return ctx.baseTypesNamespace ? namespaceEnum(expr, named as GraphQLEnumType, ctx) : expr;
  }
  return "'' /* unresolved leaf */";
}

/**
 * `enumValueExpression` emits bare `IEnum` references; in near-operation-file
 * output enums live under the `Types` namespace, so rewrite the local name to
 * the namespaced one.
 */
function namespaceEnum(expr: string, enumType: GraphQLEnumType, ctx: OpContext): string {
  const local = `${ctx.config.typesPrefix}${ctx.convertName(enumType.name)}${ctx.config.typesSuffix}`;
  return expr.split(local).join(`${ctx.baseTypesNamespace}.${local}`);
}

// --- document traversal ---------------------------------------------------------------------

function collectFragments(documents: DocumentFileLike[]): Map<string, FragmentDefinitionNode> {
  const map = new Map<string, FragmentDefinitionNode>();
  for (const def of iterateDefinitions(documents)) {
    if (def.kind === 'FragmentDefinition') map.set(def.name.value, def);
  }
  return map;
}

function* iterateDefinitions(documents: DocumentFileLike[]) {
  const seen = new Set<string>();
  for (const doc of documents) {
    if (!doc.document) continue;
    for (const def of doc.document.definitions) {
      if (def.kind === 'FragmentDefinition' || def.kind === 'OperationDefinition') {
        // De-dupe fragments/operations that near-operation-file repeats across files.
        const key = `${def.kind}:${def.name?.value ?? ''}`;
        if (def.name && seen.has(key)) continue;
        if (def.name) seen.add(key);
        yield def;
      }
    }
  }
}
